// ***** This file is deprecated and not used anymore. *****
// It is kept there for reference.


module.exports.generate = function (rng, minLength, maxLength, withSpaces) {
   var curLength = 0;
   var text = "";
   while (curLength < maxLength - 50) {
      var iSentence = Math.trunc(rng() * sentences.length);
      var sentence = cleanUpSpecialChars(sentences[iSentence], withSpaces);
      if (sentence.length > (maxLength - curLength - 20)) {
         continue;
      }
      text += sentence;
      if (withSpaces) {
         text += " ";
      }
      curLength += sentence.length;
   }
   var iLastSentence = Math.trunc(rng() * sentences.length);
   for (var iDelta = 0; iDelta < sentences.length; iDelta++) {
      var iSentence = (iLastSentence + iDelta) % sentences.length;
      var sentence = cleanUpSpecialChars(sentences[iSentence], withSpaces);
      var newLength = curLength + sentence.length;
      if ((newLength >= minLength) && (newLength <= maxLength)) {
         text += sentence;
         return text;
      }
   }
   console.log("Error : unable to generate sentences of correct length");
   return text;
}

function cleanUpSpecialChars(str, withSpaces) {
    str = str.replace(/[ÀÁÂÃÄÅ]/g,"A");
    str = str.replace(/[àáâãäå]/g,"a");
    str = str.replace(/[ÈÉÊË]/g,"E");
    str = str.replace(/[èéêë]/g,"e");
    str = str.replace(/[îï]/g,"i");
    str = str.replace(/[ôö]/g,"o");
    str = str.replace(/[ùüû]/g,"u");
    str = str.replace(/[Ç]/g,"C");
    str = str.replace(/[ç]/g,"c");
    str = str.replace(/['-]/g," ");
    str = str.replace(/[^a-zA-Z ]/gi,''); // final clean up
    if (!withSpaces) {
       str = str.replace(/[ ]/g,"");
    }
    return str.toUpperCase();
}

const sentences = [
"Essayons quelque chose",
"Qu'est-ce que tu fais",
"Qu'est-ce que c'est",
"Je serai bientôt de retour",
"Je ne sais pas",
"J'en perds mes mots",
"Ça ne va jamais finir",
"Je ne sais simplement pas quoi dire",
"C'était un méchant lapin",
"J'étais dans les montagnes",
"Est-ce que c'est une photo récente",
"Je ne sais pas si j'ai le temps",
"Pour une certaine raison le microphone ne marchait pas tout à l'heure",
"Tout le monde doit apprendre par soi-même en fin de compte",
"L'éducation dans ce monde me déçoit",
"L'apprentissage ne devrait pas être forcé. L'apprentissage devrait être encouragé",
"C'est une tâche difficile, choisir ce qui est bon ou mauvais, mais il faut le faire",
"Ça ne changera rien",
"Il se peut que j'abandonne bientôt et fasse une sieste à la place",
"C'est parce que tu ne veux pas être seul",
"Ça n'arrivera pas",
"Parfois il peut être un gars bizarre",
"Je ferai de mon mieux pour ne pas perturber tes révisions",
"Je ne peux que me demander si c'est la même chose pour tous les autres",
"Je suppose que c'est différent quand tu y penses à long terme",
"Ne t'inquiète pas",
"Tu me manques",
"Je les appellerai demain quand je reviendrai",
"J'ai toujours plus apprécié les personnages mystérieux",
"Tu devrais dormir",
"Je leur ai dit de m'envoyer un autre ticket",
"Tu es tellement impatiente avec moi",
"Je ne peux pas vivre comme ça",
"Il fut un temps où je voulais être astrophysicien",
"Je n'ai jamais aimé la biologie",
"La dernière personne à qui j'ai raconté mon idée a pensé que j'étais cinglé",
"Si le monde n'était pas dans l'état où il est maintenant, je pourrais faire confiance à n'importe qui",
"C'est malheureusement vrai",
"Ils sont trop occupés à se battre entre eux pour s'occuper d'idéaux communs",
"La plupart des gens pensent que je suis fou",
"Non je ne le suis pas, c'est toi qui l'es",
"C'est ma réplique",
"Il me donne des coups de pied",
"Est-ce que tu es sûr",
"Alors il y a un problème",
"Oh, il y a un papillon",
"Dépêche-toi",
"Ça ne me surprend pas",
"Si je pouvais être comme ça",
"Pour une certaine raison je me sens plus vivant la nuit",
"Ça dépend du contexte",
"Est-ce que tu te fous de moi",
"C'est la chose la plus stupide que j'ai jamais dite",
"Je ne veux pas être lamentable, je veux être cool",
"Quand je serai grand, je veux être roi",
"L'Amérique est un endroit charmant pour vivre, si c'est pour gagner de l'argent",
"Je ne suis pas un vrai poisson, je ne suis qu'une simple peluche",
"Je ne fais que parler",
"C'était probablement ce qui a influencé leur décision",
"Je me suis toujours demandé ce que ça ferait d'avoir des frères et soeurs",
"C'est ce que j'aurais dit",
"Ça me prendrait l'éternité pour tout expliquer",
"Parfois je ne peux pas m'empêcher de montrer des émotions",
"C'est un mot pour lequel j'aimerais trouver un substitut",
"Ce serait quelque chose qu'il faudrait que je programme",
"Il n'est pas dans mon intention d'être égoiste",
"Réfléchissons au pire qui pourrait arriver",
"Combien d'amis proches est-ce que tu as",
"Il se peut que je sois antisocial, mais ça ne veut pas dire pas que je ne parle pas aux gens",
"C'est toujours tel que ça a été",
"Je pense que c'est mieux de ne pas être impoli",
"On peut toujours trouver du temps",
"Quand je me suis réveillé j'étais triste",
"C'est ce qui est expliqué à la fin",
"Je pensais que tu aimais apprendre de nouvelles choses",
"La plupart des gens écrivent à propos de leur vie quotidienne",
"Pour faire cela, il te faut prendre des risques",
"Chaque personne qui est seule est seule parce qu'elle a peur des autres",
"Pourquoi demandes-tu",
"Je ne suis pas un artiste. Je n'ai jamais eu l'esprit pour ça",
"Je ne peux pas lui dire maintenant. Ce n'est pas si simple",
"Je suis une personne qui a des défauts, mais ces défauts peuvent être facilement corrigés",
"Chaque fois que je trouve quelque chose que j'aime, c'est trop cher",
"Combien de temps es-tu restée",
"Peut-être que ce sera la même chose pour lui",
"L'innocence est une belle chose",
"Les humains n'ont jamais été faits pour vivre éternellement",
"Je ne veux pas perdre mes idées, même si certaines d'entre elles sont un peu extrêmes",
"Je pense que j'ai une théorie à ce sujet",
"C'est intriguant",
"Tu es en train de dire que tu caches intentionnellement ta beauté",
"Je n'ai pas de compte sur ces forums",
"Si quelqu'un devait demander quel est le but de l'histoire, je ne saurais vraiment pas",
"Je ne savais pas d'où ça venait",
"Je pense que le fait que j'ai vécu avec toi a influencé la façon dont tu vis",
"Ce n'est pas important",
"Je n'ai pas aimé",
"Elle demande comment c'est possible",
"Tu ne fais que fuir les problèmes de la vie",
"Si tu regardes les paroles, elles ne signifient pas vraiment grand-chose",
"Il y a un problème que tu ne vois pas",
"Tu peux le faire",
"Mon prof de physique s'en fiche si je sèche les cours",
"J'aimerais bien pouvoir aller au Japon",
"Je déteste ça quand il y a trop de gens",
"Je dois aller au lit",
"Après ça, je pars, mais je me rends compte que j'ai oublié mon sac chez eux",
"Je ne t'en demanderai pas plus pour aujourd'hui",
"Il se peut qu'il gèle la semaine prochaine",
"Même s'il s'est excusé, je suis encore en colère",
"La police vous fera trouver les balles",
"Merci de m'avoir expliqué finalement pourquoi on me prend pour une imbécile",
"Ce n'était pas mon intention",
"Merci pour ton explication",
"Théoriquement, je suis en train de faire des maths",
"Qu'est-ce qui s'est passé",
"Ça m'a presque fait peur de ne pas te voir connectée pendant toute une journée",
"Je ne sais pas ce que tu veux dire",
"Il faut bien que mon ordinateur me serve à quelque chose",
"Tu voulais me parler de liberté",
"Si je voulais te faire peur, je te raconterais ce dont j'ai rêvé il y a quelques semaines",
"On ne peut pas tout attendre des écoles",
"Il y a beaucoup de mots que je ne comprends pas",
"Je dois te poser une question idiote",
"Je ne sais pas comment le démontrer vu que c'est trop évident",
"Est-ce qu'on peut formuler ça d'une autre manière",
"Personne ne saura",
"J'ai trouvé une solution, mais je l'ai trouvée tellement vite que ça ne peut pas être la bonne",
"Ça me paraît intéressant",
"Sauf que là, c'est pas si simple",
"Moi, j'aime bien la lumière des bougies",
"Qu'est-ce que tu as répondu",
"Non, c'est pas mon nouveau petit ami",
"C'est dommage que je n'aie pas besoin de maigrir",
"Où est le problème",
"Je ne peux qu'attendre",
"Ce n'est pas tellement une surprise, non",
"Je ne t'aime plus",
"Je suis curieux",
"Je ne veux pas attendre aussi longtemps",
"Pourquoi ne viens-tu pas nous voir",
"Mais la possibilité semble improbable",
"Je n'aurais pas dû me déconnecter",
"C'est inévitable que j'aille en France un jour, je ne sais juste pas quand",
"Je déteste la chimie",
"Je ne voulais pas que ça arrive",
"Tu devines probablement ce qui va arriver",
"Avant même que tu ne le saches, tu seras dans les journaux",
"Quelles autres options ai-je",
"Je ne suis pas un grand voyageur",
"Je n'ai rien de mieux à faire",
"Je ne peux pas l'expliquer non plus",
"Tout le monde a ses forces et ses faiblesses",
"Ça montre seulement que tu n'es pas un robot",
"Comment pourrais-je être un robot Les robots ne rêvent pas",
"Je n'y ai jamais pensé",
"Que devrions-nous faire",
"Ce n'est pas quelque chose que n'importe qui peut faire",
"Je ne sais pas si je l'ai encore",
"Qu'est-ce que tu crois que j'étais en train de faire",
"Ne sous-estime pas ma puissance",
"Ma maman ne parle pas très bien anglais",
"Je ne parle pas assez bien français",
"Je me demandais si tu allais venir aujourd'hui",
"C'est là que réside le problème",
"Comment trouves-tu de la nourriture dans l'espace",
"Vous n'avez rien à faire sauf vous faire confiance",
"Tout le monde veut te rencontrer, tu es célèbre",
"Pourquoi es-tu désolée pour quelque chose que tu n'as pas fait",
"Les étrangers m'intriguent",
"Quoique je fasse, elle dit que je peux faire mieux",
"Qu'est-ce qui te retient éveillé si tard",
"Tu serais surprise de ce que tu peux apprendre en une semaine",
"Je n'ai personne qui veuille voyager avec moi",
"La vie est dure, mais je suis encore plus dur",
"Supporter peut être insupportable",
"Arrête Tu la mets mal à l'aise",
"Rien n'est beau que le vrai",
"Demain, il va alunir",
"Je ne parle pas japonais",
"C'est un jeu de mots",
"Personne ne me comprend",
"J'ai appris à vivre sans elle",
"Ça ne sert plus à rien de continuer à réfléchir",
"J'ai trop de choses dans la tête ces jours-ci",
"Je voulais juste vérifier mes emails",
"Est-ce que tu as vraiment besoin de poser la question pour connaître la réponse",
"Tu peux pas attendre de moi que je pense toujours à tout",
"Je suppose que derrière chaque chose que l'on doit faire, il y a quelque chose que l'on veut faire",
"T'as vraiment pas les bonnes priorités",
"N'attends pas que les autres pensent pour toi",
"Tu n'as jamais le temps pour les choses importantes",
"Ce n'est pas la peine de faire semblant de me faire croire que je crois des choses que tu ne crois pas",
"Ça me prendrait trop de temps pour t'expliquer pourquoi ça ne va pas marcher",
"Je suis trop bête J'essaie de t'expliquer des choses que je ne comprends pas moi-même",
"Arrête de me considérer comme quelqu'un de normal",
"Tu pourrais au moins essayer d'être un peu plus poli, même si ce n'est pas dans ta nature",
"Il y aura toujours des choses que je n'apprendrai jamais, je n'ai pas l'éternité devant moi",
"C'est pas possible",
"Pierre qui roule n'amasse pas mousse",
"Veux-tu quelque chose à boire",
"Nous devons apprendre à vivre ensemble comme des frères, ou nous périrons ensemble comme des idiots",
"Il se peut que leur communication soit beaucoup plus complexe que nous le pensions",
"Un jour je courrai comme le vent",
"S'il te plaît, ne pleure pas",
"Fais-moi savoir s'il y a quoi que ce soit que je puisse faire",
"Il se peut que le bonheur qui nous attend là-bas ne soit pas du tout le genre de bonheur que nous voudrions",
"C'est à toi de décider si nous allons là-bas ou non",
"Ça ne commence pas avant huit heures trente",
"Je veux un bateau qui m'emmènera loin d'ici",
"Un Japonais ne ferait jamais une telle chose",
"Le communisme ne sera jamais atteint de mon vivant",
"Le seigle était appelé le grain de la pauvreté",
"Si tu vois une faute alors corrige-la s'il te plaît",
"Place le jeu de cartes sur la table en bois de chêne",
"Si on ne mange pas, on meurt",
"Et si nous retournions à la maison",
"Je m'excuse, je ne peux pas rester longtemps",
"Un million de personnes ont perdu la vie pendant la guerre",
"Je suis venu à Tokyo il y a trois ans et ai vécu ici depuis",
"D'abord, je vais faire un schéma de mon nouveau site internet",
"La démocratie est la pire forme de gouvernement, mis à part toutes les autres que l'on a essayées",
"Quand on commence à ressembler à la photo de son passeport, on devrait partir en vacances",
"C'était pas moi, commissaire",
"Oh, mon pantalon blanc Il était neuf",
"Avec autant de personnes autour de lui, il devint naturellement un peu nerveux",
"En quittant la gare, j'ai vu un homme",
"Et personne ne vous a aidé",
"T'es un ange",
"Eh bien, la nuit est très longue, n'est-ce pas",
"T'as eu de la chance parce qu'il ne t'a pas mordu",
"Je t'ai manqué",
"Sont-ils tous identiques",
"Merci beaucoup",
"S'il vous plaît, où sont les oeufs",
"Je le prends",
"C'est une surprise",
"C'est une bonne idée",
"Aller-retour Aller simple seulement",
"C'est dommage quand quelqu'un meurt",
"Ils restèrent bouche bée",
"Remettre en forme après lavage",
"Laver avant de porter pour la première fois",
"Ne pas ouvrir avant l'arrêt du train",
"Ceux qui habitent des maisons de verre ne devraient pas lancer de pierres",
"On dit que l'amour est aveugle",
"Oh, je suis désolée",
"Les maths sont comme l'amour - une idée simple, mais ça peut devenir compliqué",
"Les seules réponses utiles sont celles qui posent de nouvelles questions",
"Douter de soi est le premier signe d'intelligence",
"Un pauvre n'est pas celui qui a trop peu, mais celui qui veut trop",
"Vu que tu n'es pas surpris, je pense que tu étais au courant",
"Combien de temps cela prend-il pour arriver à la station",
"Ça sera un bon souvenir de mon voyage à travers les états-Unis",
"Excusez-moi, permettez-moi de signaler trois erreurs dans l'article ci-dessus",
"C'est difficile d'entretenir une conversation avec quelqu'un qui ne dit que oui et non",
"Est-ce que tu parles italien",
"Je ne peux pas réfléchir avec ce bruit, dit-elle, en fixant des yeux la machine à écrire",
"On dit que Hamlet est la pièce la plus intéressante qui ait jamais été écrite",
"Puis-je poser une question",
"C'est impossible pour moi de te l'expliquer",
"Je ne veux pas passer le reste de ma vie à le regretter",
"Ça serait marrant de voir comment les choses changent au fil des ans",
"Je ne l'aurais jamais deviné",
"L'imagination affecte tous les aspects de notre vie",
"Tu m'oublieras un jour",
"C'est assez inattendu",
"Je me demande combien de temps ça va prendre",
"Je ne peux pas vivre sans télé",
"Je n'aurais pas pu le faire sans toi. Merci",
"Rien n'est accompli sans effort",
"Beaucoup de gens vagabondent à travers la vie sans but",
"Faites-moi savoir si j'ai besoin de faire des changements",
"Je pense que les examens ruinent l'éducation",
"Nous ne pouvons pas dormir à cause du bruit",
"Fais tout ce qu'il te dit",
"Que veux-tu",
"On a un compte à régler",
"As-tu besoin que je te donne de l'argent",
"Paris est la ville la plus belle du monde",
"Eh, j'ai peut-être pas d'argent, mais j'ai toujours ma fierté",
"C'est mon amie Rachel, nous sommes allées au lycée ensemble",
"Le coût de la vie a augmenté radicalement",
"Tout ce qui est inventé est vrai",
"Se surprendre, s'étonner, c'est commencer à comprendre",
"Pas de doute : l'univers est infini",
"Il ne lui manquait qu'un seul défaut pour être parfaite",
"Et pourtant, le contraire aussi est toujours vrai",
"Nous ne voyons pas les choses comme elles sont, mais comme nous sommes",
"Le monde est une cage à fous",
"Aucun écolier ne se plaint jamais d'avoir mal au lobe frontal de l'hémisphère gauche",
"Tu m'as ouvert les yeux sur ce que c'est, lorsque tout va bien",
"Tu m'as trouvée où personne ne cherchait",
"Tu es à mes côtés, maintenant tout va bien",
"Comment ça, tu ne sais pas",
"T'as l'air stupide",
"Je pense que j'vais aller dormir",
"Ça me plaît beaucoup",
"On se voit demain",
"Comment est-ce qu'on dit ça en italien",
"Je dois aller faire les courses, je reviens dans une heure",
"Tu n'es pas assez rapide",
"C'est loin d'ici",
"Ce ne sont pas mes affaires",
"Merci, c'est tout",
"Veux-tu danser avec moi",
"Quelle heure est-il",
"Tu viens d'où",
"Comment est-ce que tu t'appelles",
"L'Italie est un très beau pays",
"Ce n'est pas ma faute",
"J'aimerais rester pour une nuit",
"Pourriez-vous composer le numéro pour moi Le téléphone est placé trop haut",
"Est-ce qu'il y a une auberge de jeunesse près d'ici",
"Où sont les douches",
"Ouvrez la bouche",
"C'est grave",
"J'ai perdu mon portefeuille",
"L'amour n'est jamais un gaspillage",
"La vie c'est ce qui se passe pendant que tu es occupé à faire d'autres plans",
"Ne pas désirer équivaut à posséder",
"Fiche-moi la paix",
"Passez-moi le sel s'il vous plaît",
"Il y a trop de choses à faire",
"Quel âge as-tu",
"Allez, joue avec moi, j'm'ennuie trop",
"Ne songe même pas à manger mon chocolat",
"Arrête de me demander à boire Va te servir toi-même",
"Grâce à toi j'ai perdu mon appétit",
"J'ai vraiment besoin de frapper quelqu'un",
"Qui est-ce qui ne connaît pas ce problème",
"Mes parents n'arrêtent pas de se disputer sur des choses stupides. C'est tellement énervant",
"Mes amis disent toujours que je suis trop calme, mais ma famille dit toujours que je suis trop agaçante",
"Il fait tellement chaud qu'on pourrait faire cuire des oeufs sur le capot des voitures",
"Aujourd'hui, il fait très chaud",
"Personne n'est venu",
"Je n'ai jamais vu de réfrigérateur rouge",
"Il n'a pas tenu sa parole",
"Il vaut mieux être détesté pour ce que l'on est, qu'aimé pour ce que l'on n'est pas",
"Ne sois pas inquiet, sois heureux",
"L'écurie est bien vide depuis que le cheval est mort",
"Mes yeux sont un océan dans lequel se reflètent mes rêves",
"Moi j'ai semé le vent maintenant voilà ma tempête",
"Regarde-moi quand je te parle",
"Que serait le monde sans les femmes",
"Et si tu faisais un discours et que personne ne venait",
"Je ne sais pas quoi dire pour te consoler",
"Ce n'est pas mon type",
"J'essayais de tuer le temps",
"Comment en es-tu venu à cette idée folle",
"Je suis fatigué",
"Qui veut du chocolat chaud",
"Parlez plus lentement s'il vous plaît",
"Je ne comprends pas",
"Dans combien de temps arrivons-nous",
"L'addition s'il vous plaît",
"Et qu'est-ce que nous allons faire",
"Où peut-on téléphoner",
"Je dois vous avouer que je ronfle",
"Ce soir nous allons à l'église",
"Comment vas-tu As-tu fait un bon voyage",
"Je ne me sens pas bien",
"Appelez la police",
"C'est trop cher",
"Elle fait semblant de dormir, c'est pour ça qu'elle ne ronfle pas",
"Mes chaussures sont trop petites, j'en ai besoin de nouvelles",
"On s'tire d'ici, les flics arrivent",
"Ça serait trop cool si je pouvais parler dix langues",
"Si t'es fatigué, pourquoi ne vas-tu pas dormir",
"Parce que si je vais dormir tout de suite, je me réveillerai trop tôt",
"Tu aurais dû m'écouter",
"C'est une pagaille totale, et cela me tape sur les nerfs",
"Qu'est-ce que cela implique",
"Ceux qui seront sélectionnés devront faire face à de considérables tests médicaux et psychologiques",
"Un demi-million d'enfants font encore face à la malnutrition au Niger",
"Cela prendra cinq à dix ans avant que la technologie ne soit prête",
"Les bicyclettes sont un outil pour la préservation de l'environnement urbain",
"Il serait ravi d'entendre ça",
"Que croyez-vous être vrai bien que vous ne puissiez le prouver",
"Ne demandez pas ce qu'ils pensent. Demandez ce qu'ils font",
"Quand vous essayez de prouver quelque chose, ça aide de savoir que c'est vrai",
"Ce qui change le monde, c'est la communication, pas l'information",
"Si vous ne comprenez pas quelque chose, c'est parce que vous n'êtes pas conscient de son contexte",
"On ne peut que connaître le passé, pas le changer. On ne peut que changer le futur, pas le connaître",
"La question clé n'est pas qu'est-ce que je peux gagner mais qu'est-ce que j'ai à perdre",
"Tout ce qui peut être mal compris le sera",
"Malgré l'importance du sommeil, son intérêt est un mystère",
"La passion crée de la souffrance",
"Le train venant de Genève va entrer en gare",
"Je voudrais lui offrir un cadeau pour son anniversaire",
"Je meurs de faim",
"Est-ce que tu as des copains en Antigua",
"J'ai tellement de travail que je reste une heure de plus",
"Je suis mariée et j'ai deux enfants",
"Il joue très bien du piano",
"Je le vois rarement",
"J'aimerais faire mes études à Paris",
"Vous ne savez pas qui je suis",
"Pourquoi est-ce que tu ne manges pas de légumes",
"Pourquoi est-ce que les gens vont au cinéma",
"Il n'y a pas de visions réelles",
"Le créationnisme est une pseudo-science",
"Le vent s'est calmé",
"Jeter le bébé avec l'eau du bain",
"Je ne veux pas demander ta main",
"Donne-moi du temps pour te donner tout ce que j'ai",
"Un démocrate est un citoyen libre qui se plie à la volonté de la majorité",
"Vouloir c'est pouvoir",
"Qui cherche, trouve",
"Rome ne s'est pas faite en un jour",
"Qui ne dit mot consent",
"As-tu fini Au contraire, je n'ai même pas encore commencé",
"Pourquoi est-ce qu'on dit Bonjour quand le jour n'est pas bon",
"Le vin c'est de la poésie en bouteille",
"C'était le plus beau jour de ma vie",
"Je ne comprends pas l'allemand",
"J'ai pris ma décision",
"Je te donne ma parole",
"Tu es le grand amour de ma vie",
"Nous avons un Pape",
"Le tout vaut plus que la somme de ses parties",
"Les mathématiques ne portent pas atteinte au désir",
"Une vérité mathématique n'est ni simple ni compliquée, elle est",
"Les mathématiciens sont des poètes, sauf qu'ils doivent démontrer ce que leur fantaisie crée",
"Les mathématiques sont comme la logique de la physique",
"Je ne pense pas, donc je ne suis pas",
"Je trouve les langues étrangères très intéressantes",
"Je n'aime pas apprendre les verbes irréguliers",
"Prends un livre et lis-le",
"Affronte la vie en souriant",
"Tu me fais rêver",
"Je suis fou de joie",
"C'est déjà un homme",
"Les vacances sont finies maintenant",
"J'ai peur de tomber",
"Une tenue de soirée est souhaitée",
"C'est la pure vérité",
"Il fait froid",
"J'ai soif",
"Quand on ne peut pas faire ce que l'on veut, on fait ce que l'on peut",
"Donnez-lui la main, il vous prendra le bras",
"Tu as raison",
"Tu as fait ça intentionnellement",
"Tu ne lui as rien dit",
"Tu m'as fait perdre la tête",
"Tu es mon type",
"Est-ce que tu pourrais retéléphoner plus tard s'il te plaît",
"Je parle avec qui",
"J'accepte, mais à une condition",
"Souris maintenant, pleure plus tard",
"La vie est belle",
"Ne me gâche pas mon plaisir après tout le mal que je me suis donné",
"Il y a des jours où j'ai l'impression que mon cerveau veut m'abandonner",
"Je ne peux pas me couper les ongles et faire le repassage en même temps",
"Je n'en peux plus Ça fait trois jours que je n'ai pas dormi",
"Tu as déjà mangé de la tarte à la banane",
"Si tu ne peux pas avoir d'enfants, tu peux toujours en adopter",
"Qu'est-ce qui t'a fait changer d'avis",
"Eh regarde, un singe à trois têtes",
"C'est dommage qu'on ne puisse pas acheter des miracles comme on achète des pommes de terre",
"J'adore les lasagnes",
"Le cerveau n'est qu'une machine compliquée",
"Ne désespère pas, tout n'est pas encore perdu",
"Je suis à l'hôpital. J'ai été frappé par la foudre",
"J'ai besoin que tu m'aides",
"Ce bébé pingouin est trop mignon",
"Soyons réalistes, c'est impossible. On va jamais y arriver",
"Quelle est votre plus grande source d'inspiration",
"En théorie, il n'y a pas de différence entre la théorie et la pratique",
"Ne restez pas au lit, à moins que vous ne puissiez gagner de l'argent au lit",
"Tout ce qui est trop stupide pour être dit est chanté",
"Il faut de la sagesse pour comprendre la sagesse",
"La musique n'est rien si le public est sourd",
"Je relisais les lettres que tu m'as envoyées",
"Je ne veux pas aller à l'école",
"C'est fini entre nous, rends-moi ma bague",
"Il pleut",
"J'avais prévu d'aller à la plage aujourd'hui, mais il a commencé à pleuvoir",
"Elle est vraiment intelligente, n'est-ce pas",
"Une opinion n'est choquante que lorsque c'est une conviction",
"Les gens qui aiment ne doutent de rien, ou doutent de tout",
"La justice coûte cher",
"La liberté consiste à pouvoir faire tout ce qui ne nuit pas à autrui",
"Le plus lent à promettre est toujours le plus fidèle à tenir",
"Toute opinion est un mélange de vérité et d'erreur",
"Notre opinion est une idée que nous avons ; notre conviction, une idée qui nous a",
"Demain, je vais étudier à la bibliothèque",
"Trop tard",
"Je suis allée au zoo hier",
"Nous avons gagné la bataille",
"Je prépare le déjeuner tous les jours",
"J'ai regardé la télé ce matin",
"J'ai lu un livre en mangeant",
"J'ai un peu dormi pendant la pause déjeuner parce que j'étais trop fatigué",
"J'ai commencé à apprendre le chinois la semaine dernière",
"C'est plus facile de draguer les gens sur internet que dans la rue",
"J'habite près de la mer donc j'ai souvent l'occasion d'aller à la plage",
"Un jour j'achèterai une machine à barbe-à-papa",
"C'est pratique d'avoir un ordinateur portable",
"Tes lunettes sont tombées par terre",
"Combien de fois par jour te regardes-tu dans le miroir",
"Nous sommes allés à Londres l'année dernière",
"Elle ne veut pas en parler",
"J'ai perdu mon inspiration",
"J'ai besoin de plus de temps",
"Si tu n'as rien à faire, regarde le plafond de ta chambre",
"Ça veut rien dire",
"Sois patient s'il te plaît, ça prend du temps",
"Ferme la porte en sortant",
"C'est une histoire tellement triste",
"S'il n'y a pas de solution, alors il n'y a pas de problème",
"Mon petit frère regarde la télé",
"Un fin lecteur devrait être disposé à considérer tout ce qu'il lit, y compris les sources anonymes",
"La formation et le mouvement des ouragans sont capricieux, même avec notre technologie contemporaine",
"Quand on envoie un télégramme, la brièveté est essentielle car on est facturé à chaque mot",
"Tu l'as rencontré à l'université",
"Les facultés et universités privées des états-Unis sont autonomes",
"Chaque fois que je rejoins un jeu de Warcraft, je suis opposé à une nouvelle équipe d'adversaires",
"Depuis que je sais que l'université existe, je veux y aller",
"Mon apathie pour le vote vient de mon aversion pour la politique",
"Sarah était assez perspicace pour se rendre compte que ses amis essayaient de lui faire une farce",
"L'orchestre produit des notes dissonantes lorsqu'il s'accorde",
"Oui, ça arrive de temps en temps",
"J'ai une grande peur d'être méprisé par ceux que j'aime et à qui je tiens",
"La plupart des gens ont une grande réticence à sortir de leurs lits tôt, même s'ils le doivent",
"La plupart des gens ne veulent qu'entendre leur propre vérité",
"Le public a acclamé les acteurs pour leur représentation",
"C'est bien d'avoir des idéaux tu ne penses pas",
"L'étudiant décida d'abréger son rapport en enlevant les détails inutiles",
"Les gens dans le monde se battent toujours pour plus de liberté et d'égalité",
"Les politiciens sont toujours sanctionnés pour leur comportement scandaleux ou déplacé",
"Lorsque j'ai la migraine, l'aspirine ne soulage pas la douleur pour moi",
"Ma mère préfère la sélection arbitraire des machines de loterie à mes chiffres fétiches",
"Pour lui, la faim était un concept abstrait ; il avait toujours suffisamment à manger",
"Il en avait assez d'être sans cesse diffamé par des gens qui étaient jaloux de ses capacités",
"Le roi en avait assez de ses courtisans le flattant toujours alors il les a renvoyés",
"Il y avait toujours trop de passages superficiels dans ses rédactions",
"Si je n'avais donné aucune réponse, je n'aurais pas parlé",
"Les idées de Freud sur le comportement humain l'ont amené à être honoré en tant que profond penseur",
"La prolifération de l'utilisation d'Internet a donné naissance à une nouvelle génération de jeunes",
"Mes amis disent que je suis un écrivain prolifique, mais je n'ai rien écrit depuis des mois",
"Un avare amasse de l'argent non pas parce qu'il est prudent mais parce qu'il est avide",
"Les témoins ont pu réfuter le faux témoignage du suspect",
"James avait une grande peur de faire des erreurs en classe et d'être réprimandé",
"Le proviseur réprouvait sévèrement les élèves chaque fois qu'ils mettaient le désordre dans le couloir",
"Mes parents renieraient mon frère s'ils venaient à découvrir qu'il était gay",
"Je voudrais revenir sur ma déclaration précédente",
"Tim est un énorme fan de comédie satirique",
"Tous les sujets du roi, craignant son courroux, se comportaient souvent de manière très servile",
"Les gens sont assez souvent sceptiques sur les choses sauf si on leur fournit une preuve crédible",
"Il a parfois des difficultés à exprimer clairement ses opinions",
"Jimmy essaya de persuader ses parents de le laisser traverser le pays en voiture avec ses amis",
"Les artistes de pop prospèrent sur l'adulation de leurs fans fidèles",
"Nous devons apprendre à affronter l'adversité avec grâce",
"Son ton sévère et sa voix forte masquaient sa sensibilité intérieure et sa nature attentionnée",
"Quel critère avez-vous utilisé pour élire cet essai en tant que gagnant",
"Je ne sais pas danser un pas de salsa",
"J'aime beaucoup mon travail",
"Le meurtrier fut déclaré coupable et condamné à un emprisonnement à vie",
"Parfois, les joueurs de hockey se provoquent tellement les uns les autres que des bagarres éclatent",
"Le consensus indique que nous sommes opposés à l'idée proposée",
"Un petit feu de forêt peut facilement se répandre et rapidement devenir un grand incendie",
"Je trouve que les mots ayant des définitions précises sont les plus simples à retenir",
"Il était encore furieux à propos de l'accident malgré les mots conciliants de sa femme",
"Un examen sommaire de ses dents indiqua qu'il avait la gingivite",
"L'article de journal décrivait l'accusé comme un coupable, bien qu'il avait été prouvé innocent",
"J'ai rêvé de toi",
"Il me faut un nouvel ordinateur",
"Je ne perdrai pas",
"J'étais en retard à l'école",
"Les cours reprennent bientôt",
"Je crois que je vais éternuer Passe-moi un mouchoir",
"Pendant un moment, j'ai cru qu'il était devenu fou",
"Cette journée n'a été qu'un gâchis de temps et d'argent",
"Ça m'a surpris, je ne savais pas quoi faire",
"Mais tu ne m'as jamais dit ça",
"J'ai changé la disposition de mon site",
"Quand on est petit, tout nous paraît si grand",
"Il ne me battra pas",
"Je dois faire le linge tant qu'il y a encore du soleil",
"Je me suis promenée, histoire de prendre l'air",
"T'avais plein de temps",
"Arrête de me critiquer",
"J'ai presque fini",
"Prends l'autre chaise",
"Je ne suis plus inspirée",
"Je ne m'abaisserai pas à son niveau",
"On pouvait voir le coucher du soleil depuis la fenêtre",
"Ça me rend fou",
"As-tu dit que je ne pourrais jamais gagner",
"Il fait tout noir dehors",
"Qu'est-ce qu'il s'est passé Il y a de l'eau partout dans l'appartement",
"Pendant les vacances d'été, je prenais mon dîner à minuit",
"Tu peux finir ta rédaction maintenant",
"Je suis vivant, bien que je ne donne pas signe de vie",
"Je suis trop vieux pour ce monde",
"La vie commence quand on décide ce qu'on attend d'elle",
"La vie commence quand on paie des impôts",
"Ce que tu n'as pas est mieux que ce que tu as",
"La vie commence lorsque tu es prêt à la vivre",
"Il n'est jamais trop tard pour apprendre",
"Il m'a raconté l'histoire de sa vie",
"Je n'ai jamais dit que j'étais fragile",
"Je me demande si je suis faite pour ce monde",
"De quoi parles-tu",
"Je veux un bonbon",
"Je savais qu'aujourd'hui serait amusant",
"Un enfant n'est pas un vase à remplir, mais un feu à allumer",
"Cela pourrait sembler tiré par les cheveux, mais c'est un réel problème",
"Quand est-ce qu'on mange J'ai faim",
"Je n'aime pas l'école",
"J'ai cours demain",
"Je n'arrive pas à le croire",
"L'hiver est ma saison préférée",
"C'est difficile d'avoir des idées géniales",
"De quel pays viens-tu",
"J'ai tendance à regarder les images avant de lire le texte",
"J'ai beaucoup appris de toi",
"Nous avons beaucoup marché",
"J'ai passé douze heures dans le train",
"Elle est tombée malade ce week-end",
"Attends, quelqu'un frappe à ma porte",
"Il est riche, il n'a pas besoin d'argent",
"Ils font trop de bruit, je n'arrive pas à me concentrer",
"J'ai envie d'un massage. J'ai besoin de me détendre",
"Tu es malade, tu dois te reposer",
"Il y a un passage secret à gauche",
"Je n'ai pas que ça à faire",
"Elle demande l'impossible",
"Il a disparu sans laisser de trace",
"Je peux placer la paume des mains sur le sol sans plier les genoux",
"Il ne peut pas y avoir de progrès sans communication",
"Tout le monde aimerait croire que les rêves peuvent devenir réalité",
"La meilleure façon de réaliser ses rêves est de se réveiller",
"Le monde ne tourne pas autour de toi",
"As-tu une idée de ce à quoi ma vie ressemble",
"L'atmosphère de cet endroit est mystérieuse",
"J'attends avec impatience d'entendre votre opinion sur ce sujet",
"Ma vie est vide sans lui",
"Je ne veux pas louper mes examens",
"Ma mère a acheté deux bouteilles de jus d'orange",
"Elle portait un chapeau noir",
"Nous avons fait des crêpes pour le petit-déjeuner",
"Qu'as-tu mangé au déjeuner aujourd'hui",
"J'ai passé tout l'après-midi à bavarder avec des amis",
"Je veux être plus indépendant",
"Est-ce que tu vas juste rester là debout toute la journée",
"Un lapin a de longues oreilles et une petite queue",
"Mon coeur était rempli de joie",
"Il souhaite effacer de mauvais souvenirs",
"Monsieur, vous n'avez pas le droit de garer votre voiture ici",
"Nous devons l'emmener d'urgence à l'hôpital, il est gravement blessé",
"Ton secret sera bien gardé",
"Je ne veux plus t'entendre te plaindre",
"Dis-leur de m'appeler avant qu'ils ne partent",
"Tu aurais dû refuser une proposition aussi injuste",
"Je n'ai pas la force de continuer à essayer",
"Les mathématiques ne sont pas juste de la mémorisation de formules",
"Je n'avais pas l'intention de te donner cette impression",
"Ouais J'ai gagné deux fois de suite",
"J'en ai marre de manger du fast-food",
"J'en ai marre d'en avoir marre",
"J'ai hâte de partir en vacances",
"Les chambres de cet hôtel sont vraiment très mal insonorisées",
"L'essence des mathématiques, c'est la liberté",
"Est-ce que tu peux imaginer ce que notre vie serait sans électricité",
"Où sont les toilettes",
"De combien d'heures de sommeil as-tu besoin",
"Chaque personne est un monde",
"évite d'ouvrir la fenêtre, je n'ai pas trop envie de sentir de courants d'air dans mon dos",
"J'ai la nationalité française mais je suis d'origine vietnamienne",
"C'est très frustrant d'essayer de retrouver ses lunettes quand on ne voit rien sans lunettes",
"Tu penses qu'un jour les hommes coloniseront la lune",
"Quelles chansons célèbres auriez-vous aimé avoir composées, et pourquoi",
"Je vais m'acheter un nouvel appareil photo, numérique, cette fois",
"Je suis fou de toi",
"Je ne sais pas ce qui est pire",
"Je suis fier de faire partie de ce projet",
"Est-il nécessaire d'élargir la connaissance de l'Homme à travers l'exploration de l'espace",
"La beauté réside dans les yeux de celui qui regarde",
"Qui achète ce genre d'oeuvre d'art",
"Pourquoi ne pouvons-nous pas nous chatouiller nous-mêmes",
"La réponse nous mène à un cercle vicieux",
"J'ai la flemme de faire mes devoirs",
"Quoi Tu ne sais toujours pas conduire",
"Demain c'est la rentrée Pour une fois, je suis pressé de retourner à l'école",
"Et avec moi nous sommes déjà un de plus",
"Tu as déjà de la barbe",
"Je sens que je suis libre",
"Je ressens des brûlures d'estomac",
"La liberté n'est pas gratuite",
"Le désir émerge entre nécessité et demande",
"Pendant que nous mangions le dessert, le désir de voyager vers ce pays grandissait",
"J'ai créé un raccourci sur le bureau",
"Mon frère est très important. Du moins il pense qu'il l'est",
"En mangeant une pizza, il agaçait sa soeur",
"À ce rythme, on ne risque pas de finir avant la fin de la semaine",
"Non, je ne peux pas vous laisser entrer, il y a une personne de trop",
"Où es-tu",
"Il vous fera mordre la poussière",
"Où vas-tu",
"Il fait la tête",
"Il fait une tête d'enterrement",
"Il vient de publier une série intéressante d'articles",
"Je ne fais pas forcément confiance aux traductions",
"Partager sa passion, c'est la vivre pleinement",
"Elle bouge comme une reine et démontre qu'elle a le rythme dans le sang",
"Avant-hier tu as impressionné tout le monde, mais moi, je te connaissais déjà",
"Si je te montrais ma maison, mon quartier d'alors, comprendrais-tu d'où je viens",
"La vie n'est pas longue, elle est large",
"Quand j'avais ton âge, Pluton était une planète",
"Elle est au bord de la crise de nerfs",
"Les éléphants sont les plus gros animaux terrestres vivant actuellement",
"Le temps ne permettait sans doute pas de faire une belle photo haute en couleur",
"Je te montrerai que l'on peut renaître de ses cendres",
"Si tu m'apprends à danser, je te montrerai mes cicatrices cachées",
"Les ascenseurs d'un gratte-ciel sont des systèmes vitaux",
"Un fleuve sortait d'Eden pour arroser le jardin, et là il se divisait pour former quatre bras",
"Les fruits et les légumes sont essentiels à une alimentation équilibrée",
"Je prends habituellement ma douche le soir",
"Il a passé la soirée à lire un bouquin",
"Tu as réfléchi sur ce problème toute la matinée. Prends une pause, va déjeuner",
"Si je ne le fais pas maintenant, je ne le ferai jamais",
"Bonne nuit. Fais de beaux rêves",
"Cette chanson est si émouvante que j'en ai les larmes aux yeux",
"Il y a beaucoup de choses que tu ne sais pas sur ma personnalité",
"Peut-être que tu as raison, j'ai été égoiste",
"Tout le monde mérite une seconde chance",
"Je viens de voir que l'ambassadeur de l'Arabie Saoudite à Washington a démissionné",
"Quand on demande de l'argent, il faut accepter certaines conditions",
"Quel est l'avantage de cette technologie",
"Si vous ne disposez pas de ce programme vous pouvez le télécharger maintenant",
"Le gros titre attira mon attention ce matin",
"Quand tu parles aux autres, tu le fais avec les bras croisés",
"Remplis le formulaire suivant pour savoir qui tu as pu être dans ta vie antérieure",
"La créativité est une chose importante pour le développement de l'être humain",
"Avez-vous des difficultés à comprendre ce que vous disent les femmes ou les petits enfants",
"Il ne faut pas préparer un plat différent pour chaque personne",
"On m'a dit que je suis pragmatique, et je le suis",
"Je préfère chercher une solution aux problèmes, pas seulement les dénoncer",
"Je suis à court d'idées",
"Tu continues encore à te demander quel est le sens de la vie",
"Souviens-toi que nous sommes tous dans le même bateau",
"Tout ce que j'ai besoin de savoir sur la vie, je l'ai appris d'un bonhomme de neige",
"Vérifie que ton nom d'utilisateur et ton mot de passe sont écrits correctement",
"Les adieux sont toujours tristes",
"Ne nous oublie pas",
"Le temps est passé très rapidement",
"Laquelle est votre valise",
"J'ai de la toux et un peu de fièvre",
"Ouvre l'armoire de gauche, les bouteilles sont là",
"Il y a aussi des boîtes de nuit où l'on danse le flamenco",
"L'entrée comprend une boisson",
"Je propose que l'on sorte le vendredi",
"Comme ça, je fais d'une pierre deux coups",
"Ça ne me plaît pas autant que de m'occuper des enfants",
"Avez-vous une expérience professionnelle",
"Je n'ai eu le temps ni d'aller faire les courses ni de dire au revoir à ma mère",
"J'aimerais essayer la jupe bleue rayée",
"Combien donne-t-on en pourboire en Espagne",
"Qui a peint ce tableau",
"À cette heure il y a un trafic incroyable",
"Tu n'as pas honte de parler ainsi",
"Maintenant je dois y aller, ils appellent pour mon vol",
"Il est argentin et il donne des cours de tennis",
"S'il vous plaît, indiquez-le-moi sur la carte",
"Le robinet coule",
"S'il vous plaît, dites-nous où il y a une épicerie",
"Je veux récupérer mes objets de valeur",
"Je suis enceinte de quatre mois",
"J'ai un stimulateur cardiaque",
"Je voudrais des piles pour cet appareil",
"Est-ce que je peux payer avec une carte de crédit",
"Nous avons besoin d'une ambulance",
"Nous supposons qu'il s'agit d'un empoisonnement par morsure de serpent",
"Tous les matins et tous les soirs je donne à manger à mon chat",
"Pourriez-vous répéter ça s'il vous plaît",
"En général, qui rend visite le plus à ses parents, les fils ou les filles",
"Ça te coûterait bien sûr moins cher si tu dormais chez nous",
"Vous trouverez ça dans une droguerie",
"Tout effort mérite récompense",
"Ça coûte les yeux de la tête",
"J'ai besoin de ton conseil",
"Pourtant, la chanteuse ne renie pas ses origines",
"Est-ce que tu sais par hasard où j'ai mis mes clés",
"Je me prépare au pire",
"Ça semble intéressant. Qu'est-ce que tu lui as dit",
"Je savais que c'était du plastique mais ça avait le goût du bois",
"Est-ce que je peux rester chez toi Je n'ai nulle part où aller",
"Si seulement on arrêtait d'essayer d'être heureux on pourrait passer un très bon moment",
"Prends bien soin de toi",
"Petit à petit, vous remarquerez des améliorations dans vos écrits",
"La mort n'est qu'un horizon ; et un horizon n'est rien si ce n'est la limite de notre vision",
"La seule manière sur Terre de multiplier le bonheur est de le diviser",
"Une erreur connue est meilleure qu'une vérité inconnue",
"La vie n'est pas une science exacte, c'est un art",
"Tout est théoriquement impossible jusqu'à ce que ce soit fait",
"Il se peut que tu sois déçu si tu échoues, mais tu es condamné si tu n'essaies pas",
"L'ennui est le sentiment que tout est une perte de temps ; la sérénité, que rien ne l'est",
"Il n'y a pas de distance sur cette terre aussi éloignée qu'hier",
"Seuls ceux qui se risqueront à aller trop loin saurons jusqu'où on peut aller",
"Tout homme prend les limites de son propre champ de vision pour les limites du monde",
"Nous le faisons à une vitesse remarquable d'une seconde par seconde",
"Le réel problème n'est pas de savoir si les machines pensent mais si les hommes le font",
"Mon intérêt se porte sur le futur parce que je vais passer le reste de ma vie là-bas",
"Le monde est un livre, et ceux qui ne voyagent pas ne lisent qu'une seule page",
"Le problème avec beaucoup de choses sont les idées préconçues que nous avons à leur sujet",
"Je comprends ce que tu es en train de dire",
"La meilleure façon de prédire l'avenir est de l'inventer",
"Si l'on savait ce que l'on faisait, ça ne s'appellerait pas de la recherche, non",
"Pour celui qui n'a qu'un marteau dans sa trousse à outils, tout problème ressemble à un clou",
"Rien n'est impossible pour celui qui n'a pas à le faire lui-même",
"Je pense que c'est bien que les livres existent encore, mais ils me donnent bien envie de dormir",
"Je ne comprends pas pourquoi les gens sont effrayés par les nouvelles idées",
"L'espoir n'est pas une stratégie",
"Adressez-vous à mon collègue",
"Le dossier a été adressé au ministère",
"Ils ne sont courageux qu'en paroles",
"Ils t'attendent devant la porte",
"Tu as un crayon sur toi",
"À qui est-ce",
"Depuis que Mario m'a menti, je ne lui adresse plus la parole",
"C'est une bonne affaire",
"Ce n'est pas son affaire",
"Ramasse tes affaires et va-t'en",
"C'est une sale affaire",
"Il est tiré d'affaire",
"Il faut faire suivre l'acte à la parole",
"Je ne me le fais pas dire deux fois",
"Baissez les mains",
"Rira bien qui rira le dernier",
"Le plus tôt sera le mieux",
"Ce n'est pas tout à fait exact",
"Il ne fait pas son âge",
"Tu aimes le rap",
"J'aime les voyages",
"D'où viens-tu",
"Je ne m'attendais vraiment pas à ça de ta part",
"J'attends depuis des heures",
"Il mourut très âgé",
"Nous sommes ce que nous prétendons être, donc il nous faut faire attention à ce que nous prétendons être",
"Je ne le connais pas",
"Ce film m'a plu",
"Elle est toute cousue d'or",
"Ça m'est égal",
"J'allais sortir quand le téléphone a sonné",
"Regarde bien. Je vais te montrer comment on fait",
"Je vais faire les courses tous les matins",
"Les gens doivent comprendre que le monde évolue",
"La parole est d'argent mais le silence est d'or",
"Le fleuve a inondé toute la région",
"Le problème s'est résolu tout seul",
"Ces propos me déplaisent",
"Vous n'êtes pas du tout concerné",
"Ce sont des opinions tout à fait opposées",
"Quel âge avez-vous",
"Je ne suis pas du tout convaincu",
"Pourquoi voulez-vous partir aujourd'hui",
"Je vais prendre ma voiture",
"C'est trop beau pour être vrai",
"On ne peut pas accomplir l'impossible sans tenter l'absurde",
"Le meilleur moyen de prendre un train à l'heure, c'est de s'arranger pour rater le précédent",
"Il ne faut compter que sur soi-même. Et encore, pas beaucoup",
"Se taire en classe, c'est respecter le sommeil des autres",
"La logique est une méthode systématique pour arriver à la mauvaise conclusion en toute confiance",
"Nous apprenons par expérience que les hommes n'apprennent jamais rien par expérience",
"Mieux vaut tard que jamais",
"Bon début promet bonne fin",
"Tel père, tel fils",
"Péché avoué est à moitié pardonné",
"Tant qu'il y a de la vie, il y a de l'espoir",
"Je ne l'ai pas fait exprès",
"Tous les chemins mènent à Rome",
"L'avenir appartient à ceux qui se lèvent tôt",
"Dans la vie il y a des hauts et des bas",
"Tous les goûts sont dans la nature",
"On ne peut pas être au four et au moulin",
"On n'a rien sans rien",
"Un homme averti en vaut deux",
"Les mots s'envolent, les écrits restent",
"La nuit tous les chats sont gris",
"Tout finit par se payer",
"La musique adoucit les moeurs",
"Apprends-moi comment on fait",
"Qui va à la chasse perd sa place",
"La vérité sort de la bouche des enfants",
"Pas de nouvelles, bonnes nouvelles",
"Toute peine mérite salaire",
"On n'est jamais si bien servi que par soi-même",
"Si vous pensez que l'éducation coûte cher, attendez de voir ce que l'ignorance vous coûte",
"L'état n'a pas su répondre à l'attente des citoyens",
"Je m'y attendais",
"Je n'attends rien de ta part",
"Attendez dans la salle d'attente",
"Plus de gens se mettent dans le pétrin pour les choses qu'ils disent plutôt que pour ce qu'ils font",
"Pourquoi attaches-tu de la valeur à cet incident",
"Attention, Monsieur, ça glisse",
"Les gens qui mentiront pour vous, vous mentiront",
"Il n'y a aucun doute",
"Il n'y a aucune solution",
"Je ne savais pas qu'il buvait autant",
"Toute activité que vous voulez accomplir prendra plus de temps que vous n'en avez",
"C'est bien fait",
"Tu veux un jus de fruit",
"C'est quelqu'un de bien",
"Fais comme bon te semble",
"Bon appétit",
"Ils ont beau étudier, ils sont toujours recalés",
"Il n'y a point d'amours sans jalousie",
"Il n'y avait pas âme qui vive",
"Nous sommes de même farine",
"Loin des yeux, loin du coeur",
"Les murs ont des oreilles",
"J'ai un chat dans la gorge",
"Ça m'énerve de ne pas trouver où est mon erreur de calcul",
"Ce n'est pas encore tout à fait ça mais je crois qu'on se rapproche de la solution",
"Faites comme chez vous",
"En général, on en sait peu sur les équations différentielles non linéaires du second ordre",
"Le Mali est l'un des pays les plus pauvres de l'Afrique subsaharienne",
"Pourquoi est-ce que tu ne viens pas avec nous",
"Je ne peux pas dire le contraire",
"Pourquoi tu me parles d'hippopotames tout d'un coup",
"Je ne vois pas le rapport entre ça et tes douze poissons rouges",
"Ne l'écoute pas, il raconte n'importe quoi",
"Tu ne peux pas te perdre dans les grandes villes, il y a des plans partout",
"Nous sommes désolés, la personne que vous essayez de contacter n'est pas disponible",
"Je n'en veux plus",
"Il est venu plusieurs fois",
"On se demande pourquoi",
"On doit penser aux amis",
"Je vais me baigner",
"Nous sommes partis avec la pluie mais nous sommes arrivés avec le soleil",
"Nous sommes partis en train",
"Si on mange trop on grossit",
"Je ne sais pas s'il l'aurait fait pour moi",
"Aimerais-tu venir",
"Je savais qu'il accepterait",
"Elle serait venue volontiers mais elle était en vacances",
"Je croyais que c'était vrai",
"Voici la ville dont je te parlais",
"Voici le garçon à qui je pense",
"On l'a averti à plusieurs reprises",
"Je dois rendre le livre avant samedi",
"Nous nous sommes tellement efforcés d'améliorer les choses pour nos enfants que nous les avons empirées",
"Salut, je voulais juste te faire savoir que le problème est réglé",
"Comment tu peux avoir un ordinateur portable et pas de téléphone portable",
"Je suis allé boire une bière avec des amis",
"Il a sauté par la fenêtre",
"Hier, nous nous sommes bien amusés",
"Elles se sont disputées",
"J'ai mangé du caviar",
"Il a beaucoup changé depuis la dernière fois",
"Ce couteau m'a beaucoup servi",
"Vous vous êtes trompé de clé",
"J'ai réssi à entrer",
"Ça coûte combien",
"Vous acceptez les cartes de crédit",
"Je vous apporte l'addition tout de suite",
"Voici votre monnaie",
"Je paierai par chèque",
"Tu as laissé un pourboire",
"N'oubliez pas le ticket de caisse",
"Je regrette, je n'ai pas de monnaie",
"La situation est pire qu'on ne le croyait",
"Il faut s'attendre au pire",
"Ils ne savent même pas pourquoi",
"Excusez-moi, je me suis trompé de numéro",
"Je voudrais que tu me dises la vérité",
"Tu es arrivée au moment où je sortais",
"Ce n'est pas grave, je ne lui en veux pas",
"À qui le dis-tu",
"Qui vient avec moi",
"Je veux savoir qui vient avec nous",
"Florence est la ville la plus belle d'Italie",
"Debout les enfants",
"J'ai fait de bons achats",
"J'ai rencontré des personnes sympathiques",
"J'ai parlé à des amis",
"Je suis content de te revoir",
"Tu as beaucoup changé",
"Ceux qui le connaissent l'apprécient",
"Dis-moi ce qui est arrivé",
"Il ne fait que pleurer",
"Ce sont des jeunes filles sérieuses",
"Comme tu es belle",
"Il y a autant de musées que d'églises",
"Il est plus facile de s'amuser que de travailler",
"Tu dois travailler davantage",
"C'est plus difficile que tu ne crois",
"Il m'a dit qu'il irait à Venise",
"Qui sont ces types-là",
"Nous avons réssi",
"Je ne suis pas d'accord avec lui",
"L'esprit est fort mais la chair est faible",
"Il y a pas mal de choses à faire, tu veux de l'aide",
"Il me semble que le train est en retard",
"Une fois les vacances terminées, il faut penser au travail",
"Il a appris la nouvelle en lisant le journal",
"Que cela te plaise ou non, il faudra que tu le fasses",
"Je ne sais pas si j'aurai le temps de le faire",
"Demande à Trang s'il sort ce soir",
"Elle a le teint clair alors que son frère a la peau foncée",
"Dans une ville on peut passer inaperçu, alors que dans un village c'est impossible",
"Qui a dit ça C'est complètement faux",
"Quand j'étais petit, je passais des heures à lire tout seul dans ma chambre",
"Normalement, les loups n'attaquent pas les gens",
"Veuillez fermer la porte en sortant",
"La voiture ne veut pas démarrer",
"Ah Si j'étais riche, je m'achèterais une maison en Espagne",
"Si seulement elle arrêtait de jouer cette musique idiote",
"Pourvu qu'il puisse venir J'aimerais le voir",
"Ils n'accepteront jamais, c'est trop loin",
"Son jardin est une oeuvre d'art",
"Je préférerais être un oiseau plutôt qu'un poisson",
"L'eau gèle à zéro degré, n'est-ce pas",
"Si vous prenez soin des petites choses, les grandes choses prendront soin d'elles-mêmes",
"Laisse tomber. Ça n'en vaut pas la peine",
"Celui qui ne travaille pas n'a pas le droit de manger",
"On va beaucoup manger ce soir alors j'espère que tu ne fais pas de régime",
"Il a neigé toute la nuit"
];
